os: osx
osx_image: xcode9.4
language: node_js
node_js: "8"
sudo: required

env:
  global:
    # from https://www.electron.build/configuration/publish#githuboptions
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - PUBLISH_FOR_PULL_REQUEST=false
    - USE_HARD_LINKS=false
    - YARN_GPG=no

# specifying npm version as
# by default travis seemed to sue 4.2.0
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-a-specific-npm-version

install:
  - node --version
  - npm i -g npm@5
  - npm --version
  - npm install

cache:
  npm: true
  node: true

script:
  - travis_wait 60 npm run build:mwl:publish:always;
  - ls ./dist;
  - find . | grep .dmg;
  - find . | grep .AppImage;
  - find . | grep .exe;

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/