name: Electron

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: npm install
      - name: Publish
        run: npm run build:m:publish:always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
